/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distritocp.Cliente;

import ModeloDistrito.ConsultasDistrito;
import distritocp.sat.acceso;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alberto
 */
public class asignaciones extends javax.swing.JPanel {
private Integer  idUsuario;
    /**
     * Creates new form asignaciones
     */
    
     public void setId(Integer idUsuario) {

        this.idUsuario = idUsuario;

    }

    public Integer getId() {

        return idUsuario;

    }

    
    
    
        public void mostrarDatosClientes (Integer idUsuario){
        String Valor = "";
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre del Acceso");
        modelo.addColumn("Nombre del Sitio");
        modelo.addColumn("Usuario");
        modelo.addColumn("Entrar al Acceso");
        tbCliente.setModel(modelo);
        consultas.mostrasDatosCliente(Valor, modelo, tbCliente,idUsuario);
        tbCliente.setEnabled(false);
        tbCliente.setRowHeight(30);
        tbCliente.getColumnModel().getColumn(0).setPreferredWidth(3);
        tbCliente.getTableHeader().setReorderingAllowed(false);
    }
    
    
    
    public asignaciones() {
     initComponents();
     
    
    }

 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("Asignaciones");

        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClienteMouseClicked
        // TODO add your handling code here:
       int colum = tbCliente.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tbCliente.getRowHeight();
        String idAsignacion = String.valueOf(tbCliente.getValueAt(row, 0));
        Integer IDAsignacion = Integer.parseInt(idAsignacion);
         String cuenta = consultas.obtenerCuenta(IDAsignacion);
        if (row < tbCliente.getRowCount() && row >= 0 && colum < tbCliente.getColumnCount() && colum >= 0) {
            Object value = tbCliente.getValueAt(row, colum);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("entrarCliente")) {
                       removeAll();
                    revalidate();
                    repaint();
                    String usuarioAcceso = String.valueOf(tbCliente.getValueAt(row, 3));
                   // System.out.print(usuarioAcceso);
                    String contrasenaUser = consultas.obtenerContrasena(IDAsignacion);
                    String url = consultas.obtenerURL(IDAsignacion);
                    verificacionAcceso.setCuenta(cuenta);
                    verificacionAcceso.setVisible(true);
                    verificacionAcceso.setUsuario(usuarioAcceso);
                    verificacionAcceso.setContrasena(contrasenaUser);
                    verificacionAcceso.setURL(url);
                    verificacionAcceso.setIDUsuario(idUsuario);
                    String acceso = "accesoAdmin"; 
                    verificacionAcceso.setAcceso(acceso);
                }

            }
        }     
        
    }//GEN-LAST:event_tbClienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tbCliente;
    // End of variables declaration//GEN-END:variables
   ConsultasDistrito  consultas = new ConsultasDistrito();
    acceso verificacionAcceso = new acceso();
 
}
