/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distritocp.sat;

/**
 *
 * @author DistritoCP
 */
import ModeloDistrito.ConsultasDistrito;
import distritocp.Cliente.accesosAsignados;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import personalDigital.digitalPersonal;

public class acceso extends javax.swing.JFrame {

    public String usuario;
    public String contrasena;
    public String url;
    public Integer IDUsuario;
    public  String acceso;
    public  String cuenta; 
    /**
     * Creates new form acceso
     */
    public void setUsuario(String Usuario) {
        this.usuario = Usuario;

    }

    public String getUsuario() {

        return usuario;
    }

    public void setContrasena(String Contrasena) {
        this.contrasena = Contrasena;

    }

    public String getContrasena(String Contrasena) {
        return contrasena;
    }

    public void setURL(String url) {
        this.url = url;

    }

    public String getURL() {
        return url;

    }

    public void setIDUsuario(Integer IDUsuario) {
        this.IDUsuario = IDUsuario;

    }

    public Integer getIDUsuario() {
        return IDUsuario;

    }
    
    public void  setAcceso(String acceso){
       this.acceso = acceso ; 
    
    }
    
    public String  getAcceso(){
            return acceso ; 
                     
    }
    
    
    public void setCuenta(String cuenta){
        this.cuenta = cuenta ; 
    }
    
    public String getCuenta(){
       return cuenta;
    
    }
    

    public acceso() {
        initComponents();
        setDefaultCloseOperation(0);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        this.setResizable(false);
        personalDigital.setEstado(lblEstados);
        personalDigital.setEvento(lblEventos);
        personalDigital.setHuella(lblHuellas);
        personalDigital.setFrameVerificacion(this);
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/bloggif_588f8648a7d00.png"));
        lblHuellas.setIcon(icon);
        lblEventos.setText("Verifique su Acceso");

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEstados = new javax.swing.JLabel();
        lblHuellas = new javax.swing.JLabel();
        lblEventos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verificacion");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloggif_588a21aa9b845.png"))); // NOI18N

        lblHuellas.setToolTipText("");
        lblHuellas.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblEventos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEventos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEventos.setToolTipText("");

        jLabel2.setText("Estado del Sensor");

        btnCerrar.setText("Cerrrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblHuellas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCerrar)
                                .addGap(140, 140, 140))))
                    .addComponent(lblEventos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(lblEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHuellas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           
// TODO add your handling code here:
        //IDUsuario = getIDUsuario();
        //ResultSet  datosSitios =  distritoConsulta.obtenerAcceso(url, usuario, contrasena);
        personalDigital.setNombreUsuario(usuario);
        personalDigital.setContrasena(contrasena);
        personalDigital.setUrl(url);
        personalDigital.setIDUsuarioAcceso(IDUsuario);
        personalDigital.setAcceso(acceso);
        personalDigital.setCuenta(cuenta);
        personalDigital.Iniciar();
        personalDigital.start();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/bloggif_588f8648a7d00.png"));
        lblHuellas.setIcon(icon);
        lblEventos.setText("Verifique su Acceso");

    }//GEN-LAST:event_formWindowOpened

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

          personalDigital.stop();
         this.setVisible(false);
      

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        this.removeAll();
//        this.revalidate();
//        this.repaint();
        personalDigital.stop();
        this.setVisible(false);
        


    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acceso().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEstados;
    private javax.swing.JLabel lblEventos;
    private javax.swing.JLabel lblHuellas;
    // End of variables declaration//GEN-END:variables
 digitalPersonal personalDigital = new digitalPersonal();
 ConsultasDistrito distritoConsulta = new ConsultasDistrito();

}
