/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distritocp.sat;

import BD.conexionBD;
import ControladorDistrito.ControllerDistrito;
import ControladorDistrito.sitios;
import ModeloDistrito.ConsultasDistrito;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import personalDigital.digitalPersonal;

/**
 *
 * @author Alberto
 */
public final class actualizacion extends javax.swing.JFrame {

    private Integer idAsignacion;
    private Integer idUsuario;
    private Integer idAcceso;
   
    void llenar_combo() {
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        consultas.Sitios(modeloCombo,cboAccesos);

    }

    void llenarCampo() {
        Integer AsignacionID = getAsignacion();
        JTextField model = new JTextField();
        consultas.llenarCampo(AsignacionID, txtNombre, txtUsuario, txtContrasena,txtAccesoFiel,cboAccesos);

    }

    /**
     * Creates new form actualizacion
     */
    public actualizacion() {
      
        this.setResizable(false);
        initComponents();
         setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
          setDefaultCloseOperation(0);
        llenar_combo();
        llenarCampo();
     
        personalDigital.setFrameActualizar(this);
//        personalDigital.Iniciar();
//        personalDigital.start();
    }

    public void setidAsigacion(Integer IdAsignacion) {
        this.idAsignacion = IdAsignacion;

    }

    public Integer getAsignacion() {
        return idAsignacion;
    }

    public void SetidUsuario(Integer idUsuario) {

        this.idUsuario = idUsuario;
    }

    public Integer getidUsuario() {

        return idUsuario;
    }

    public void SetidAcceso(Integer idAcceso) {

        this.idAcceso = idAcceso;
    }

    public Integer getidAcceso() {

        return idAcceso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnSalirActualizacion = new javax.swing.JButton();
        cboAccesos = new javax.swing.JComboBox<>();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAccesoFiel = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actualizacion");
        setLocation(new java.awt.Point(500, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setText("Nombre del Acceso");

        jLabel4.setText("Pagina de Acceso");

        jLabel5.setText("Usuario");

        jLabel6.setText("Contraseña");

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloggif_5893bec57c5de.png"))); // NOI18N
        btnModificar.setToolTipText("");
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnModificar.setLabel("Actualizar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnSalirActualizacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalirActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloggif_5893bfe1801a5.png"))); // NOI18N
        btnSalirActualizacion.setText("Cerrar");
        btnSalirActualizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActualizacionActionPerformed(evt);
            }
        });

        cboAccesos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAccesosItemStateChanged(evt);
            }
        });

        txtContrasena.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Actualizacion de Datos");

        jLabel1.setText("Cuenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(40, 40, 40)
                                .addComponent(cboAccesos, 0, 241, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(57, 57, 57)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtAccesoFiel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(50, 50, 50)
                        .addComponent(btnSalirActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(169, 169, 169))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboAccesos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(txtAccesoFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirActualizacion)
                    .addComponent(btnModificar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            String nombre = txtNombre.getText();
            sitios paginas = (sitios) cboAccesos.getSelectedItem();
            Integer paginasID = paginas.getID();
            String usuario = txtUsuario.getText();
            String contrasena = new String(txtContrasena.getPassword());
           String accesoFiel= txtAccesoFiel.getText();
           JTextField txtAccesoFielCaja = txtAccesoFiel;
           if (distritoController.validacionCampos(nombre, usuario, contrasena,accesoFiel,txtAccesoFielCaja)) {
          JOptionPane.showMessageDialog(null, "Favor de llenar los datos requeridos", "Ocurrio Un Error", JOptionPane.WARNING_MESSAGE);
          } else {
                Integer IDAcceso = getidAcceso();
                Integer IDAsignacion = getAsignacion();
                Integer IDUsuario = getidUsuario();
              if (consultas.actualizarAcceso(IDAcceso, nombre, usuario, contrasena)) {
                    if (consultas.actualizarAsignaciones(IDAsignacion, IDUsuario, paginasID)) {
                      JOptionPane.showMessageDialog(null, "Se realizo la actualizacion", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                      System.out.println("Actualizado");
                      this.setVisible(false);
                      controlAcceso  principal = new controlAcceso();
                      principal.setVisible(true);
                 } else {
                       JOptionPane.showMessageDialog(null, "No se realizo la actualizacion", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se realizo la actualizacion", "Error", JOptionPane.ERROR_MESSAGE);
              }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor de llenar los datos requeridos", "Ocurrio Un Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActualizacionActionPerformed
       this.setVisible(false);
      //Integer IDUsuario = getidUsuario();
//      principal.setVisible(true);
//      principal.setID(IDUsuario);

    }//GEN-LAST:event_btnSalirActualizacionActionPerformed

    private void cboAccesosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAccesosItemStateChanged
        int eleccion  = cboAccesos.getSelectedIndex();
    if(eleccion == 0){
     txtAccesoFiel.setEnabled(false);
       txtAccesoFiel.setText("");
    
    }
    
    if(eleccion == 2){
        txtAccesoFiel.setEnabled(true);
     }else if (eleccion == 1){
       txtAccesoFiel.setEnabled(false);
       txtAccesoFiel.setText("");
       
     }else if (eleccion == 3){
       txtAccesoFiel.setEnabled(false);
       txtAccesoFiel.setText("");
     
     }else if (eleccion ==  4){
        txtAccesoFiel.setEnabled(false);
       txtAccesoFiel.setText("");
     }else if (eleccion == 5){
       txtAccesoFiel.setEnabled(false);
       txtAccesoFiel.setText("");
     
     }
     
     
    }//GEN-LAST:event_cboAccesosItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        ImageIcon icon = new ImageIcon("C:\\Users\\Alberto\\Documents\\NetBeansProjects\\DistritoCP-SAT\\src\\imagenes\\bloggif_588f8648a7d00.png");
        llenarCampo();

    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actualizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalirActualizacion;
    private javax.swing.JComboBox<String> cboAccesos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField txtAccesoFiel;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
//conexionBD con = new conexionBD();
// Connection c = con.conectar();
   ConsultasDistrito  consultas = new ConsultasDistrito();
   ControllerDistrito  distritoController = new ControllerDistrito();
   digitalPersonal   personalDigital = new digitalPersonal();
  // controlAcceso  principal = new controlAcceso();
}
