/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distritocp.sat;
import ControladorDistrito.accesosActivos;
import ControladorDistrito.asignacion;
import ModeloDistrito.ConsultasDistrito;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DistritoCP
 */
public class asignaciones extends javax.swing.JPanel {
public Integer idUsuario;

public void setIDUsuario(Integer idUsuario){

this.idUsuario = idUsuario ; 

}


public Integer getIDUsuario (){
     
  return idUsuario ; 

}

    /**
     * Creates new form Asignaciones
     */
    
    
    void llenar_comboUsuario(){
         DefaultComboBoxModel modeloUsuario = new DefaultComboBoxModel(); 
         consultas.ObtenerUsuarios(modeloUsuario, cboUsuario);
    }
    
    void llenar_comboAcceso(){
      DefaultComboBoxModel modeloAcceso = new DefaultComboBoxModel(); 
      consultas.obtenerAcceso(modeloAcceso,cboAccesos);
    
    } 

    public void  mostrarAsignaciones(String Valor){
     DefaultTableModel modelo = new DefaultTableModel();
      modelo.addColumn("ID");
      modelo.addColumn("Nombre Usuario Asignado");
      modelo.addColumn("Nombre del Acceso");
      modelo.addColumn("Nombre del Sitio");
      modelo.addColumn("Usuario");
      modelo.addColumn("Eliminar Asignacion"); 
      tbAsignaciones.setModel(modelo);
      consultas.mostrarAsingaciones(Valor, modelo, tbAsignaciones);
        tbAsignaciones.setEnabled(false);
        tbAsignaciones.setRowHeight(30);
        tbAsignaciones.getColumnModel().getColumn(0).setPreferredWidth(3);
        tbAsignaciones.getTableHeader().setReorderingAllowed(false);
      
    }


    
    public asignaciones() {
        initComponents();
       // menuDistrito principal = new menuDistrito();
        llenar_comboUsuario();
        llenar_comboAcceso();
         mostrarAsignaciones("");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        cboAccesos = new javax.swing.JComboBox<>();
        cboUsuario = new javax.swing.JComboBox<>();
        btnAsignar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAsignaciones = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Nombre del Acceso");

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario");

        cboUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUsuarioActionPerformed(evt);
            }
        });

        btnAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asignacionesq.png"))); // NOI18N
        btnAsignar.setText("Asignar Usuario");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        tbAsignaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbAsignaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAsignacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAsignaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboAccesos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(326, 326, 326))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboAccesos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(31, 31, 31)
                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUsuarioActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
     try{
     asignacion usuarios = (asignacion)cboUsuario.getSelectedItem();
     Integer idUsuario = usuarios.getIdUsuario();
     accesosActivos accesos = (accesosActivos)cboAccesos.getSelectedItem(); 
     Integer idAcceso = accesos.getIDAcceso(); 
     Integer idAsignacion = consultas.setIDAsignacion(idAcceso); 
     if(consultas.actualizarAsignacion(idAsignacion, idUsuario, idAcceso)){
       System.out.println("actulizado"); 
       mostrarAsignaciones("");
        cboUsuario.setSelectedIndex(0);
        cboAccesos.setSelectedIndex(0);
     }else{
      JOptionPane.showMessageDialog(null, "No se logro asignar el acceso", "Ocurrio Un Error", JOptionPane.WARNING_MESSAGE);    
     
     }
     
     }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor de llenar los datos requeridos", "Ocurrio Un Error", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void tbAsignacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAsignacionesMouseClicked
        // TODO add your handling code here:ç
        int colum = tbAsignaciones.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tbAsignaciones.getRowHeight(); 
        String  idAsignacion = String.valueOf(tbAsignaciones.getValueAt(row, 0));
        Integer  IDAsignacion = Integer.parseInt(idAsignacion);
       if(row < tbAsignaciones.getRowCount() && row >= 0  && colum < tbAsignaciones.getColumnCount() && colum >= 0 ) {
           Object value = tbAsignaciones.getValueAt(row, colum);
         if(value instanceof JButton){
         ((JButton) value).doClick();
          JButton boton = (JButton) value;
             
       if(boton.getName().equals("eliminarAsignacion")){
        if(consultas.asignacionesEliminadas(IDAsignacion, idUsuario)){
            System.out.println("eliminado");
            mostrarAsignaciones("");
        
        }
       
       }
       }  
       }
    }//GEN-LAST:event_tbAsignacionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JComboBox<String> cboAccesos;
    private javax.swing.JComboBox<String> cboUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tbAsignaciones;
    // End of variables declaration//GEN-END:variables

    ConsultasDistrito  consultas  = new ConsultasDistrito(); 
    asignacion     usuarios  = new asignacion(); 
    accesosActivos  accesos = new accesosActivos(); 
    
}
