/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distritocp.sat;

/**
 *
 * @author DistritoCP
 */

import ControladorDistrito.sitios;
import ModeloDistrito.ConsultasDistrito;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ControladorDistrito.ControllerDistrito;
import java.awt.TextField;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class controlAcceso extends javax.swing.JPanel {

    public Integer idUsuario;

    /**
     * Creates new form Accesos
     */
    public void setID(Integer id) {

        this.idUsuario = id;

    }

    public Integer getID() {

        return idUsuario;

    }

    public void datosVerificacion(String usuarioAcceso, String contrasenaUser, String url, Integer idUsuario,String cuenta) {
        verificacionAcceso.setCuenta(cuenta);
        verificacionAcceso.setUsuario(usuarioAcceso);
        verificacionAcceso.setContrasena(contrasenaUser);
        verificacionAcceso.setURL(url);
        verificacionAcceso.setIDUsuario(idUsuario);

    }

    void llenar_combo() {
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        consultas.Sitios(modeloCombo, cboAcceso);

    }

    public void mostrarDatos(String valor) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre de Acceso");
        modelo.addColumn("Sitio");
        modelo.addColumn("Usuario");
        modelo.addColumn("contraseña");
        modelo.addColumn("Modificar");
        modelo.addColumn("Eliminar");
        modelo.addColumn("Accesar");
        modelo.addColumn("Ver Contraseña");
        tbDatos.setModel(modelo);
        consultas.mostrarDatos(valor, modelo, tbDatos);
        tbDatos.setEnabled(false);
        tbDatos.setRowHeight(30);
        tbDatos.getColumnModel().getColumn(0).setPreferredWidth(3);
        tbDatos.getTableHeader().setReorderingAllowed(false);

    }

    public controlAcceso() {
        
        initComponents();
        llenar_combo();
        mostrarDatos("");
        txtAccesoFiel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSitio = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        contrasena = new javax.swing.JLabel();
        txtAcceso = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnGuardare = new javax.swing.JButton();
        btnLimpiare = new javax.swing.JButton();
        cboAcceso = new javax.swing.JComboBox<>();
        btnVerificare = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAccesoFiel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nombre Acceso");

        lblSitio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSitio.setText("Pagina Acceso");

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario");

        contrasena.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        contrasena.setText("Contraseña");

        txtAcceso.setToolTipText("");

        btnGuardare.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloggif_588a2b79a8e0b.png"))); // NOI18N
        btnGuardare.setText("Guardar Acceso");
        btnGuardare.setToolTipText("");
        btnGuardare.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnGuardare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardareActionPerformed(evt);
            }
        });

        btnLimpiare.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpiare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloggif_588a2cdce9de0.png"))); // NOI18N
        btnLimpiare.setText("Limpiar campos");
        btnLimpiare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiareActionPerformed(evt);
            }
        });

        cboAcceso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAccesoItemStateChanged(evt);
            }
        });

        btnVerificare.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVerificare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloggif_588b711e0bc43.png"))); // NOI18N
        btnVerificare.setText("Verificar ");
        btnVerificare.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVerificare.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVerificare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificareActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Cuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(btnGuardare)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiare)
                .addGap(18, 18, 18)
                .addComponent(btnVerificare, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(contrasena)))
                    .addComponent(lblSitio))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAcceso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(txtAccesoFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSitio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtAccesoFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contrasena))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiare)
                    .addComponent(btnVerificare, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardareActionPerformed
        try {
            sitios paginas = (sitios) cboAcceso.getSelectedItem();
            Integer IdPagina = paginas.getID();
            String nombreAcceso = txtAcceso.getText();
            String Usuario = txtUsuario.getText();
            String contrasena = new String(txtContrasena.getPassword());
            String accesoFiel= txtAccesoFiel.getText();
            JTextField txtAccesoFielCaja = txtAccesoFiel;
            if (distritoController.validacionCampos(nombreAcceso, Usuario, contrasena,accesoFiel,txtAccesoFielCaja )) {
                JOptionPane.showMessageDialog(null, "Favor de llenar los datos requeridos", "Ocurrio Un Error", JOptionPane.WARNING_MESSAGE);
            } else {
                if (consultas.GuardarAccesos(nombreAcceso, Usuario, contrasena,accesoFiel)) {
                    Integer IDAcceso = consultas.setAccesos();
                    if (consultas.GuardarAsignaciones(idUsuario, IdPagina, IDAcceso)) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron almacenados", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                        txtAcceso.setText("");
                        txtUsuario.setText("");
                        txtContrasena.setText("");
                        cboAcceso.setSelectedIndex(0);
                        mostrarDatos("");

                    } else {
                        JOptionPane.showMessageDialog(null, "El sitio no fue almacenado", "Ocurrio Un Error", JOptionPane.WARNING_MESSAGE);

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "El sitio no fue almacenado", "Ocurrio Un Error", JOptionPane.WARNING_MESSAGE);

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor de llenar los datos requeridos", "Ocurrio Un Error", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnGuardareActionPerformed

    private void btnLimpiareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiareActionPerformed
        txtAcceso.setText("");
        txtUsuario.setText("");
        txtContrasena.setText("");
        cboAcceso.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiareActionPerformed

    private void btnVerificareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificareActionPerformed
        try {
            String nombreAcceso = txtAcceso.getText();
            sitios paginas = (sitios) cboAcceso.getSelectedItem();
            String acceso = paginas.geturl();
            String usuario = txtUsuario.getText();
            String contrasena = new String(txtContrasena.getPassword());
            String accesoFiel =  txtAccesoFiel.getText();
            JTextField txtAccesoFielCaja = txtAccesoFiel;
            if (distritoController.validacionCampos(nombreAcceso, usuario, contrasena,accesoFiel,txtAccesoFielCaja)) {
                JOptionPane.showMessageDialog(null, "Favor de llenar los datos requeridos", "Ocurrio Un Error", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Ejecutando Acceso", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                distritoController.acessoPlataformas(usuario, contrasena, acceso,accesoFiel);
                JOptionPane.showMessageDialog(null, "Acceso Ejecutado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor de llenar los datos requeridos", "Ocurrio Un Error", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_btnVerificareActionPerformed

    private void tbDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatosMouseClicked
        int colum = tbDatos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tbDatos.getRowHeight();
        String idAsignacion = String.valueOf(tbDatos.getValueAt(row, 0));
        Integer IDAsignacion = Integer.parseInt(idAsignacion);
        Integer accesosID = consultas.obtenerIDAcceso(IDAsignacion);
        
        String usuarioAcceso = String.valueOf(tbDatos.getValueAt(row, 3));
        String contrasenaUser = consultas.obtenerContrasena(IDAsignacion);
        String url = consultas.obtenerURL(IDAsignacion);
        String cuenta = consultas.obtenerCuenta(IDAsignacion);
        if (row < tbDatos.getRowCount() && row >= 0 && colum < tbDatos.getColumnCount() && colum >= 0) {
            Object value = tbDatos.getValueAt(row, colum);

            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("eliminar")) {

                    int s = JOptionPane.showConfirmDialog(null, "Eliminar Acceso", "Si/No", JOptionPane.YES_NO_OPTION);
                    if (s == 0) {

                        if (consultas.eliminarAsignacion(IDAsignacion)) {

                            if (consultas.eliminarAcceso(accesosID)) {
                                JOptionPane.showMessageDialog(null, "Acceso Eliminado Exitosamente ", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                                mostrarDatos("");

                            }
                        }

                    }
                }
                if (boton.getName().equals("modificar")) {
                    removeAll();
                    revalidate();
                    repaint();
                    if (actualizaciones != null) {
                        actualizaciones.setVisible(true);
                        actualizaciones.setidAsigacion(IDAsignacion);
                        actualizaciones.SetidUsuario(idUsuario);
                        actualizaciones.SetidAcceso(accesosID);

                    } else {
                        actualizaciones.dispose();
                        System.out.println("esta abierto");

                    }

                }

                if (boton.getName().equals("entrar")) {
                   if( verificacionAcceso !=null){
    
                   verificacionAcceso.setVisible(true);
                    removeAll();
                    revalidate();
                    repaint();
                    String acceso = "accesoAdmin";
                    datosVerificacion(usuarioAcceso, contrasenaUser, url, idUsuario,cuenta);
                    verificacionAcceso.setAcceso(acceso);
                   }else{
                      verificacionAcceso.dispose();
                   
                   } 
                    
                }
                
                if(boton.getName().equals("verContrasena")){
                  removeAll();
                  revalidate();
                  repaint();
                    verificacionAcceso.setVisible(true);
                  String acceso = "verContrasenas";
                  datosVerificacion(usuarioAcceso, contrasenaUser, url, idUsuario,cuenta);
                  verificacionAcceso.setAcceso(acceso);

                }
                
            }
        }

    }//GEN-LAST:event_tbDatosMouseClicked

    private void cboAccesoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAccesoItemStateChanged
    int eleccion  = cboAcceso.getSelectedIndex();
    if(eleccion == 0){
     txtAccesoFiel.setEnabled(false);
       txtAccesoFiel.setText("");
    
    }
    
    if(eleccion == 2){
        txtAccesoFiel.setEnabled(true);
     }else if (eleccion == 1){
       txtAccesoFiel.setEnabled(false);
       txtAccesoFiel.setText("");
       
     }else if (eleccion == 3){
       txtAccesoFiel.setEnabled(false);
       txtAccesoFiel.setText("");
     
     }else if (eleccion ==  4){
        txtAccesoFiel.setEnabled(false);
       txtAccesoFiel.setText("");
     }else if (eleccion == 5){
       txtAccesoFiel.setEnabled(false);
       txtAccesoFiel.setText("");
     
     }
     
     

    }//GEN-LAST:event_cboAccesoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardare;
    private javax.swing.JButton btnLimpiare;
    private javax.swing.JButton btnVerificare;
    private javax.swing.JComboBox<String> cboAcceso;
    private javax.swing.JLabel contrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSitio;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tbDatos;
    private javax.swing.JTextField txtAcceso;
    private javax.swing.JTextField txtAccesoFiel;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    //accesos ControllerUser = new accesos();
//    actualizacion idActualizacion = new actualizacion();
    ControllerDistrito distritoController = new ControllerDistrito();
    sitios paginas = new sitios();
    ConsultasDistrito consultas = new ConsultasDistrito();
    acceso verificacionAcceso = new acceso();
    actualizacion actualizaciones = new actualizacion();
 
}
