/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distritocp.sat;

/**
 *
 * @author DistritoCP
 */

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import personalDigital.digitalPersonal;


public class menuDistrito extends javax.swing.JFrame {
//public  JFrame control;
    //creacionAcceso controles = new creacionAcceso (); 

    public Integer id;
    
    /**
     * Creates new form menuDistrito
     */
    public void setID(Integer id) {

        this.id = id;

    }

    public Integer getID() {

        return id;

    }
    

    
    
    

    public menuDistrito() {
        initComponents();
        this.setResizable(false);
        setDefaultCloseOperation(0);
         setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
         //int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
       //int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
       // this.setBounds((ancho / 2) - (this.getWidth() / 2), (alto / 2) - (this.getHeight() / 2),1000,750);
         this.setMinimumSize(new Dimension(300,250)); 
        /* lblCuerpo.paintAll(lblCuerpo.getGraphics());    
      lblCuerpo.add(controles,BorderLayout.CENTER);
      controles.setSize(1000,550);
     controles.setAlignmentX(120);
     controles.setAlignmentY(100);
      controles.setID(id);
         */
    }
    
 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnAcceso = new javax.swing.JButton();
        btnAsignacion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblCreacion = new javax.swing.JLabel();
        lblAsignacion = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblCuerpo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DistritoCP- SAT");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloggif_588a21aa9b845.png"))); // NOI18N

        btnAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloggif_58893d6d54d0a.png"))); // NOI18N
        btnAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoActionPerformed(evt);
            }
        });

        btnAsignacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloggif_58893eb46d4c4.png"))); // NOI18N
        btnAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloggif_58894172683ef.png"))); // NOI18N
        btnSalir.setToolTipText("");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblCreacion.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblCreacion.setText("Creacion de Acessos");

        lblAsignacion.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblAsignacion.setText("Asignacion de Accesos");

        lblSalir.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblSalir.setText("Salir");

        javax.swing.GroupLayout lblCuerpoLayout = new javax.swing.GroupLayout(lblCuerpo);
        lblCuerpo.setLayout(lblCuerpoLayout);
        lblCuerpoLayout.setHorizontalGroup(
            lblCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lblCuerpoLayout.setVerticalGroup(
            lblCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCreacion))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(btnAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(lblAsignacion)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(lblSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(btnSalir)))
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addGap(481, 481, 481))))
            .addComponent(lblCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreacion))
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAsignacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoActionPerformed
         
        controlAcceso controles = new controlAcceso();
        lblCuerpo.removeAll();
        lblCuerpo.revalidate();
        lblCuerpo.paintAll(lblCuerpo.getGraphics());
//  creacionAcceso controles = new creacionAcceso (); 
        lblCuerpo.add(controles, BorderLayout.CENTER);
        controles.setSize(1000, 550);
        controles.setAlignmentX(120);
        controles.setAlignmentY(100);
        controles.setID(id);
        
    }//GEN-LAST:event_btnAccesoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionActionPerformed
        
        asignaciones asignar = new asignaciones();
        lblCuerpo.removeAll();
        lblCuerpo.revalidate();
        lblCuerpo.paintAll(lblCuerpo.getGraphics());
        lblCuerpo.add(asignar, BorderLayout.CENTER);
        asignar.setSize(1000, 550);
        asignar.setAlignmentX(120);
        asignar.setAlignmentY(100);
        asignar.setIDUsuario(id);
     
    }//GEN-LAST:event_btnAsignacionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        controlAcceso controles = new controlAcceso();
        lblCuerpo.removeAll();
        lblCuerpo.revalidate();
        lblCuerpo.paintAll(lblCuerpo.getGraphics());
        lblCuerpo.add(controles, BorderLayout.CENTER);
        controles.setSize(1000, 550);
        controles.setAlignmentX(120);
        controles.setAlignmentY(100);
        controles.setID(id);
   
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuDistrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceso;
    private javax.swing.JButton btnAsignacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblAsignacion;
    private javax.swing.JLabel lblCreacion;
    private javax.swing.JPanel lblCuerpo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSalir;
    // End of variables declaration//GEN-END:variables
 digitalPersonal personalDigital = new digitalPersonal();
 
}
